version: "3.8"
services:
  consul:
    image: consul:latest
    ports:
      - "8300:8300"
      - "8400:8400"
      - "8500:8500"
      - "8600:53/udp"
    restart: always

  frontend:
    environment:
      - TLS
    build: .
    image: hotel_reserv_frontend_single_node
    entrypoint: frontend
    container_name: hotelreservation_frontend
    ports:
      - "5000:5000"
    depends_on:
      - consul
    restart: always

  profile:
    environment:
      - TLS
    build: .
    image: hotel_reserv_profile_single_node
    entrypoint: profile
    container_name: hotelreservation_profile
    ports:
      - "8081:8081"
    depends_on:
      - mongodb-profile
      - memcached-profile
      - consul
    restart: always

  search:
    build: .
    image: hotel_reserv_search_single_node
    entrypoint: search
    container_name: hotelreservation_search
    ports:
      - "8082:8082"
    depends_on:
      - consul
    restart: always
    environment:
      - TLS
      # - GRPC_GO_LOG_VERBOSITY_LEVEL=2
      # - GRPC_GO_LOG_SEVERITY_LEVEL=info

  geo:
    environment:
      - TLS
    build: .
    container_name: hotelreservation_geo
    entrypoint: geo
    container_name: 'hotel_reserv_geo'
    ports:
      - "8083:8083"
    depends_on:
      - mongodb-geo
      - consul
    restart: always

  rate:
    environment:
      - TLS
    build: .
    image: hotel_reserv_rate_single_node
    entrypoint: rate
    container_name: hotelreservation_rate
    ports:
      - "8084:8084"
    depends_on:
      - mongodb-rate
      - memcached-rate
      - consul
    restart: always

  recommendation:
    environment:
      - TLS
    build: .
    image: hotel_reserv_recommend_single_node
    entrypoint: recommendation
    container_name: hotelreservation_recommendation
    ports:
      - "8085:8085"
    depends_on:
      - mongodb-recommendation
      - consul
    restart: always

  user:
    environment:
      - TLS
    build: .
    image: hotel_reserv_user_single_node
    entrypoint: user
    container_name: hotelreservation_user
    ports:
      - "8086:8086"
    depends_on:
      - mongodb-user
      - consul
    restart: always

  reservation:
    environment:
      - TLS
    build: .
    image: hotel_reserv_rsv_single_node
    entrypoint: reservation
    container_name: hotelreservation_reservation
    ports:
      - "8087:8087"
    depends_on:
      - mongodb-reservation
      - memcached-reserve
      - consul
    restart: always

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: 'hotel_reserv_jaeger'
    ports:
      - "14269"
      - "5778:5778"
      - "14268:14268"
      - "14267"
      - "16686:16686"
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
    restart: always
    cpuset: "17"

  memcached-rate:
    image: memcached
    hostname: rate-memcached
    container_name: hotelreservation_memcached-rate
    ports:
     - 11212:11211
    restart: always
    environment:
      - MEMCACHED_CACHE_SIZE=128
      - MEMCACHED_THREADS=2
    logging:
      options:
        max-size: 50m

  memcached-profile:
    image: memcached
    hostname: profile-memcached
    container_name: hotelreservation_memcached-profile
    ports:
     - 11213:11211
    restart: always
    environment:
      - MEMCACHED_CACHE_SIZE=1024
      - MEMCACHED_THREADS=4
    logging:
      options:
        max-size: 50m

  memcached-reserve:
    image: memcached
    hostname: reserve-memcached
    ports:
     - 11214:11211
    restart: always
    environment:
      - MEMCACHED_CACHE_SIZE=1024
      - MEMCACHED_THREADS=4
    logging:
      options:
        max-size: 50m

  mongodb-geo:
    image: mongo:4.2.15
    container_name: hotelreservation_mongodb-geo
    hostname: geo-db
    ports:
      - "27018:27017"
    restart: always
    cpuset: "11"
    volumes:
      - geo:/data/db  

  mongodb-profile:
    image: mongo:4.2.15
    container_name: hotelreservation_mongodb-profile
    hostname: profile-db
    ports:
      - "27019:27017"
    restart: always
    volumes:
      - profile:/data/db    

  mongodb-rate:
    image: mongo:4.2.15
    hostname: rate-db
    ports:
      - "27020:27017"
    restart: always
    volumes:
      - rate:/data/db   

  mongodb-recommendation:
    image: mongo:4.2.15
    hostname: recommendation-db
    container_name: hotelreservation_mongodb-recommendation
    ports:
      - "27021:27017"
    restart: always
    volumes:
      - recommendation:/data/db
    
  mongodb-reservation:
    image: mongo:4.2.15
    container_name: hotelreservation_mongodb-reservation
    hostname: reservation-db
    ports:
      - "27022:27017"
    restart: always
    volumes:
      - reservation:/data/db 

  mongodb-user:
    image: mongo:4.2.15
    container_name: hotelreservation_mongodb-user
    hostname: user-db
    ports:
      - "27023:27017"
    restart: always
    volumes:
      - user:/data/db

        # test:
        #environment:
        #  - TLS
        #image: bbeckwi2/testmdb
        #container_name: 'hotel_reserv_test'
        #depends_on:
        #  - mongodb-geo
        #  - consul
        #restart: always
        #cpuset: "17"
    
volumes:
  geo:
  profile:
  rate:
  recommendation:
  reservation:
  user:

